### ISSUE TITLE
Add Raspberry Pi Support

### ISSUE THREAD

**Issue by Omar8345** [hitblast/ArduinoFireDetector#2]
Maybe add Raspberry Pi Support? It would be great as I would love to test this.

Probably focus on RP 4/5, as they are the most popular and it's mostly possible to do most stuff on it. 👍

**Comment by hitblast** [comment]
@Omar8345 Hey pal!

Sorry for not being able to respond. My socials (e.g. Discord, iMessage) are having some problems regarding connectivity so I am currently able to use them. I'll definitely reply to all the things you've sent when the issue resolves.

**Comment by hitblast** [comment]
> Hey!
> 
> What social or app can we chat one? Let me know.
> 
> Thanks :)

@Omar8345 Currently I'm only reachable via GitHub and mobile only. I'll tell you here once I create a new social / my old ones are accessible again. Oh, and I'll look into the Raspberry support thingy! ;)

**Comment by Omar8345** [comment]
> > Hey!
> > What social or app can we chat one? Let me know.
> > Thanks :)
> 
> @Omar8345 Currently I'm only reachable via GitHub and mobile only. I'll tell you here once I create a new social / my old ones are accessible again. Oh, and I'll look into the Raspberry support thingy! ;)

Great 👍 - If your email works, email me on the public email linked to my GitHub profile.

**Comment by Omar8345** [comment]
Hey!

Did you fix any of your socials? We have to continue working on our project.
